### ISSUE TITLE
Version numbering scheme.

### ISSUE THREAD

**Issue by nleclerc** [mattrayner/cordova-plugin-vuforia-sdk#3]
Hey, i think major version for this plugin should match major version of the underlying sdk, otherwise it'll quickly become confusing.
No need to follow minor or revision though.

**Comment by dsgriffin** [comment]
@mattrayner What do you think about this? I could bump the version to 6.0.0 for the SDK upgrade

**Comment by mattrayner** [comment]
I think we should bump it to the exact version of the SDK - it will be
easier to track that way

**Comment by nleclerc** [comment]
I would vote against using exact SDK version not only because ios and android vesions don't match (like android having 6.0.117 but ios still at 6.0.112) but also because it doesn't leave room for updates that are not sdk version upgrades (like cordova related stuff maybe).

Major version only should be just fine don't you think ?

**Comment by mattrayner** [comment]
I get what you're saying - I guess in the future we'll diverge away, accorind to the official release notes the Vuforia 'version' is 6.0.117 - the fact that not everything applies specifically to all platforms is mute?

When they do the next version we'll make a move to be more generic again - for now we're stuck at 6.0.117 ><
